---
plugin: amazon.aws.aws_ec2

regions:
  - ap-south-1

filters:
  tag:Application: nodejs-app
  instance-state-name: running

keyed_groups:
  - key: tags.Environment
    prefix: env
  - key: placement.availability_zone
    prefix: az

hostnames:
  - ip-address

compose:
  ansible_host: public_ip_address
  ansible_user: ubuntu
  ansible_ssh_private_key_file: /home/ubuntu/masterkey.pem