---
- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Create nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/{{ app_name }}.conf
    mode: '0644'
  notify: restart nginx

- name: Remove default nginx configuration
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Ensure nginx is enabled and started
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Configure nginx in firewall
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - http
    - https
  ignore_errors: yes